services:
  app:
    build: .
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPORT: 5051
      POSTGRES_PORT: 5051
    ports:
      - "5051:5051"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
